[features]
seeds = false
skip-lint = false

[programs.localnet]
paylock_escrow = "BgWSFpXL2tzGTk2N8ihVF5WdNM3q9e9jRuMLJGKWnBA8"

[programs.devnet]
paylock_escrow = "BgWSFpXL2tzGTk2N8ihVF5WdNM3q9e9jRuMLJGKWnBA8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
