[features]
seeds = false
skip-lint = false

[programs.devnet]
paylock_escrow = "BgWSFpXL2tzGTk2N8ihVF5WdNM3q9e9jRuMLJGKWnBA8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
